### ISSUE TITLE
Adding new cucumber tests fail the autograder

### ISSUE THREAD

**Issue by JacksonGL** [saasbook/hw-bdd-tdd-cycle#12]
Sometimes when students add cucumber tests, the autograder gives 0 credit for the cucumber tests and rspec tests in the student's submission.

See the following links:
[https://piazza.com/class/ihnzrrneapa3o3?cid=415](https://piazza.com/class/ihnzrrneapa3o3?cid=415)
[https://piazza.com/class/ihnzrrneapa3o3?cid=428](https://piazza.com/class/ihnzrrneapa3o3?cid=428)
[https://piazza.com/class/ihnzrrneapa3o3?cid=433](https://piazza.com/class/ihnzrrneapa3o3?cid=433)
[https://piazza.com/class/ihnzrrneapa3o3?cid=445](https://piazza.com/class/ihnzrrneapa3o3?cid=445)
[https://piazza.com/class/ihnzrrneapa3o3?cid=441](https://piazza.com/class/ihnzrrneapa3o3?cid=441)

**Comment by zhangaaron** [comment]
I'm going to attach actual files since Piazza isn't going to be visible some people in the saasbook org and move this to the autograder since this appears to be an autograder issue.
