### ISSUE TITLE
orphaned migration

### ISSUE THREAD

**Issue by tansaku** [saasbook/hw-bdd-tdd-cycle#13]
From Rose

> I noticed when working on HW4 that there was an orphaned migration showing up
when I did a rake db:migrate:status.
Originally forked it to my repo, then cloned it to my c9
Went through the process again, and again this strange orphaned migration still showed up
(wanted to verify that it wasn't from something I did, although at that point I really hadn't done anything anyway!)

> Correct me if I'm wrong, but I'm not sure that it's such a good idea to give this to students without fixing it. -- Or at least giving them a hint that they should perform a validation before beginning their work    :~)

**Comment by armandofox** [comment]
what does 'orphaned' mean?

Armando Fox
Professor, Computer Science Division
Faculty Advisor, UC Berkeley MOOCLab
fox .at. cs .dot. berkeley .dot. edu
581 Soda Hall MC#1776, Berkeley, CA 94720-1776
+1.510.642.6820 / http://www.cs.berkeley.edu/~fox

TAKE MY CLASS FOR FREE VIA edX:  http://saas-class.org  
LIKE IT ON FACEBOOK:  http://facebook.com/saas-class
TRY MY BOOK (NOT FREE): http://www.saasbook.info (goes with the course)

**Comment by tansaku** [comment]
@armandofox I think it means we have a migration stored in the db that has no corresponding file in the codebase:

```
[tansaku@Samuels-MBP:~/Documents/GitHub/saasbook/hw-bdd-tdd-cycle/rottenpotatoes (master)]$ 
→ rake db:migrate:status

database: /Users/tansaku/Documents/GitHub/saasbook/hw-bdd-tdd-cycle/rottenpotatoes/db/development.sqlite3

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20111119180638  Create movies
   up     20120130161449  ********** NO FILE **********

[tansaku@Samuels-MBP:~/Documents/GitHub/saasbook/hw-bdd-tdd-cycle/rottenpotatoes (master)]$ 
→ rake db:migrate:status RAILS_ENV=test

database: /Users/tansaku/Documents/GitHub/saasbook/hw-bdd-tdd-cycle/rottenpotatoes/db/test.sqlite3

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20111119180638  Create movies
   up     20120130161449  ********** NO FILE **********

```

**Comment by rosewcs345** [comment]
I created a pull request that corrects it, complete with documentation

**Comment by tansaku** [comment]
this one right? https://github.com/saasbook/hw-bdd-tdd-cycle/pull/15

**Comment by rosewcs345** [comment]
Yes, that's the one.

**Comment by rosewcs345** [comment]
Yes, that's the one.


On Mon, Apr 11, 2016 at 4:56 AM, Sam Joseph <notifications@github.com>
wrote:

> this one right? #15 <https://github.com/saasbook/hw-bdd-tdd-cycle/pull/15>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/saasbook/hw-bdd-tdd-cycle/issues/13#issuecomment-208238192>
>



-- 
-- 

*Rose Williams*

*Lecturer*

*Department of Computer Science*

*Binghamton University*

*(607) 777-7702*

*-----------------------------------------------*


*We are what we think.  *

*All that we are arises** with*
* our thoughts.  *

*With our thoughts,** we** make the world.*



*Shakyamuni** Buddha*
